### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by Antony-Lester** [Brett-Parker/streamdeck-satisfactory#1]
can we get a write up on the readme on how to implement/install

**Comment by Brett-Parker** [comment]
Hi @Antony-Lester, this is still a work in progress but I will update the readme with the installation.

**Comment by Brett-Parker** [comment]
Sorry for the delay @Antony-Lester , life has got in the way... There is now a release and the readme has been update on the main page;

Release: https://github.com/Brett-Parker/streamdeck-satisfactory/releases
Readme: https://github.com/Brett-Parker/streamdeck-satisfactory
